//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockSatGraphIt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RockSatGraphIt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string AlertTitle {
            get {
                return ResourceManager.GetString("AlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error extracting archive... .
        /// </summary>
        internal static string ArchiveExtractError {
            get {
                return ResourceManager.GetString("ArchiveExtractError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure??.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Destination. Files will reside in a folder called &quot;Rocksat-C Launch Data&quot;.
        /// </summary>
        internal static string DataDirectorySelectMessage {
            get {
                return ResourceManager.GetString("DataDirectorySelectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import numpy as np
        ///import pylab
        ///import mahotas as mh
        ///import os
        ///import os.path
        ///import math
        ///import sys
        ///
        ///def newprint(message):
        ///	print(message)
        ///	sys.stdout.flush()
        ///	
        ///
        ///
        ///def main():
        ///    #imageDir = &quot;d:/sandbox&quot;
        ///    #outputDir = &quot;d:/sandbox&quot;
        ///    #outputFilename = &quot;test&quot;
        ///    #extension = &quot;.JPG&quot;
        ///    #totalFileCount = 40
        ///    #outputExtension = &quot;.txt&quot;
        ///
        ///    imageDir = &quot;__imageDirectory__&quot;
        ///    outputDir = &quot;__outputDirectory__&quot;
        ///    outputFilename = &quot;__outputFilename__&quot;
        ///    extension = &quot;__imageExtension__&quot;
        ///    totalFileC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DemoSatStep1 {
            get {
                return ResourceManager.GetString("DemoSatStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR STEP 1 SCRIPT FIX....
        /// </summary>
        internal static string DemoSatStep1FixError {
            get {
                return ResourceManager.GetString("DemoSatStep1FixError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import numpy as np
        ///import pylab
        ///import mahotas as mh
        ///import os
        ///import math
        ///import sys
        ///
        ///def newprint(message):
        ///    print(message)
        ///    sys.stdout.flush()
        ///
        ///def main():
        ///    imageDir = &quot;__imageDirectory__&quot;
        ///    outputDir = &quot;__outputDirectory__&quot;
        ///    outputFilename = &quot;__outputFilename__&quot;
        ///    extension = &quot;__imageExtension__&quot;
        ///    totalFileCount = __totalFileCount__
        ///    percentCompleteStep = 100.0 / totalFileCount
        ///
        ///    newprint(&quot;Calculating max pixel count for each image&quot;)
        ///    pylab.gray()
        ///    filename = open(outputDi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DemoSatStep2 {
            get {
                return ResourceManager.GetString("DemoSatStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR STEP 2 SCRIPT FIX....
        /// </summary>
        internal static string DemosatStep2FixError {
            get {
                return ResourceManager.GetString("DemosatStep2FixError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist... Create?.
        /// </summary>
        internal static string DirectoryDoesntExist {
            get {
                return ResourceManager.GetString("DirectoryDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty fields....
        /// </summary>
        internal static string EmptyFieldError {
            get {
                return ResourceManager.GetString("EmptyFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields must be filled out... Sorry!.
        /// </summary>
        internal static string EmptyFieldsError {
            get {
                return ResourceManager.GetString("EmptyFieldsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close this window?.
        /// </summary>
        internal static string ExitMessage {
            get {
                return ResourceManager.GetString("ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string ExitTitle {
            get {
                return ResourceManager.GetString("ExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File must end in a .csv extension... sorry!.
        /// </summary>
        internal static string InvalidFileExtension {
            get {
                return ResourceManager.GetString("InvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid graph type....
        /// </summary>
        internal static string InvalidGraphType {
            get {
                return ResourceManager.GetString("InvalidGraphType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters aren&apos;t numbers, silly....
        /// </summary>
        internal static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid output type....
        /// </summary>
        internal static string InvalidOutputType {
            get {
                return ResourceManager.GetString("InvalidOutputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time must be greater than 0....
        /// </summary>
        internal static string InvalidStartTime {
            get {
                return ResourceManager.GetString("InvalidStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MissionPatch {
            get {
                object obj = ResourceManager.GetObject("MissionPatch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MissionPatch_noback {
            get {
                object obj = ResourceManager.GetObject("MissionPatch_noback", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon nasa {
            get {
                object obj = ResourceManager.GetObject("nasa", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null download destination path.... this should be impossible....
        /// </summary>
        internal static string NullDownloadDest {
            get {
                return ResourceManager.GetString("NullDownloadDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper bounds must exceed lower bounds...
        /// </summary>
        internal static string NumericalBoundsError {
            get {
                return ResourceManager.GetString("NumericalBoundsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Python34 {
            get {
                object obj = ResourceManager.GetObject("Python34", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] R {
            get {
                object obj = ResourceManager.GetObject("R", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##RockSat-C 2016 Graphing Utility
        ///##Author: David Colclazier
        ///##GPL V2
        ///##RScript.exe source is available at https://github.com/wch/r-source
        ///##To Run, tweak the tweakables, select all (Ctrl-A) and press (Ctrl-R) within RGui.
        ///##Download RGui from... INSERT LINK
        ///##RScript.exe is licensed by
        ///
        ///#clear variables from previous session (dev-use only I think)
        ///rm(list = setdiff(ls(), lsf.str()))
        ///
        ///cat(&quot;Beginning Graph Creation... Please wait.\n&quot;);
        ///
        ///#TWEAKABLE VARIABLES - INPUT
        ///
        ///fileName = &quot;__Filename__&quot;   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RScriptTemplate {
            get {
                return ResourceManager.GetString("RScriptTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating R script....
        /// </summary>
        internal static string ScriptGenerationError {
            get {
                return ResourceManager.GetString("ScriptGenerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close this window? Running tasks will be cancelled..
        /// </summary>
        internal static string SureTasksWillCancel {
            get {
                return ResourceManager.GetString("SureTasksWillCancel", resourceCulture);
            }
        }
    }
}
